version: '3.8'
services:
  postgres:
    image: postgres:14.4-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example