name: NestJS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: test
      TYPEORM_USERNAME: tester
      TYPEORM_PASSWORD: tester
      TYPEORM_DATABASE: example
      TYPEORM_PORT: 5432
      TYPEORM_ENTITIES: src/**/*/*.entity.ts
      TYPEORM_MIGRATIONS: migrations/*.ts
    services:
      postgres:
        image: postgres:14.4
        env:
          POSTGRES_USER: tester
          POSTGRES_PASSWORD: tester
          POSTGRES_DB: example
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'

    - name: Install    
      run: npm install

    - name: Tests
      run: npm test
